# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  user: fred
  password: 
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: fred_development

test:
  <<: *default
  database: fred

production:
  <<: *default
  database: fred_production
  username: fred
  password: <%= ENV['FRED_DATABASE_PASSWORD'] %>